version: "3.8"
services:
  tawarruq_app:
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 2
    hostname: tawarruq_app
    labels:
      app: tawarruq_app
    container_name: tawarruq_app
    image: tawarruq_app:latest
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    networks:
      - app_network
      - db

  tawarruq_nginx:
    container_name: tawarruq_nginx
    image: tawarruq_nginx:latest
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./public:/usr/src/app/public
      - type: bind
        source: ./storage/app/public
        target: /usr/src/app/public/storage
    ports:
      - 9300:80
    depends_on:
      - tawarruq_app
    environment:
      NGINX_FPM_HOST: tawarruq_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  # tawarruq_redis:
  #   deploy:
  #     replicas: 1
  #     resources:
  #       limits:
  #         memory: 2G
  #       reservations:
  #         memory: 256M
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       max_attempts: 3
  #       window: 120s
  #     update_config:
  #       parallelism: 2
  #   hostname: tawarruq_redis
  #   labels:
  #     app: tawarruq_redis
  #   container_name: tawarruq_redis
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - app_network
#  tawarruq_worker:
#    deploy:
#      replicas: 1
#      resources:
#        limits:
#          memory: 2G
#        reservations:
#          memory: 256M
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#        window: 120s
#      update_config:
#        parallelism: 2
#    hostname: tawarruq_worker
#    labels:
#      app: tawarruq_worker
#    container_name: tawarruq_worker
#    image: tawarruq_app:latest
#    networks:
#      - db
#    command: php artisan queue:work
#    volumes:
#      - .:/usr/src/app
#    depends_on:
#      - tawarruq_app

networks:
  app_network:
    driver: overlay
  db:
    external: true
